# Generated by Django 5.2.3 on 2025-06-18 01:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workoutplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutPlan',
            new_name='WorkoutSession',
        ),
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'verbose_name': 'Workout Session', 'verbose_name_plural': 'Workout Sessions'},
        ),
    ]
