# Generated by Django 5.2.3 on 2025-06-20 00:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_rename_workoutplan_workoutsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
